version: '3.8'
services:
  log-postgres:
    image: postgres:13
    container_name: log_postgres
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpassword
    ports:
      - "5433:5432"
    volumes:
      - log_postgres_data:/var/lib/postgresql/data

  user-postgres:
    image: postgres:13
    container_name: user_postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5434:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: session_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  log_postgres_data:
  user_postgres_data:
  redis_data: