server:
  port: 0
spring:
  application:
    name: auth-service
    version: @buildVersion@
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: db_username
    password: db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost